import argparse
import os
import shutil
import traceback
import sys
from datetime import datetime
from pathlib import Path

from .focus_config import set_focus_enabled
from .focused_schema import apply_focused_schema_file
from .shared import (
    BASE_CONTENT,
    CODEC_CONTENT,
    EXPORTED_CLASS_CONTENT,
    EXTRA_ROOT_CLASS_NAMES,
    OUTPUT_DIR,
    ROOT_CLASS_NAME,
    SCHEMA_OUTPUT_DIR,
    SCRIPT_NAME,
    UNITY_STRUCTS_CONTENT,
    load_assemblies,
)
from .type_processor import TypeProcessor


def run(
    *,
    game: Path,
    output_dir: Path,
    schema_output_dir: Path,
    full_schema: bool = False,
    full_classes: bool = False,
) -> None:
    # Compact mode is default: focus is enabled unless full classes are requested.
    set_focus_enabled(not full_classes)

    output_dir_str = str(output_dir.expanduser().resolve())
    schema_output_dir_str = str(schema_output_dir.expanduser().resolve())
    class_name = ROOT_CLASS_NAME

    if os.path.exists(output_dir_str):
        shutil.rmtree(output_dir_str)
    os.makedirs(output_dir_str, exist_ok=True)
    if os.path.exists(schema_output_dir_str):
        shutil.rmtree(schema_output_dir_str)
    os.makedirs(schema_output_dir_str, exist_ok=True)

    try:
        load_assemblies(str(game))

        with open(os.path.join(output_dir_str, "MessagePackBase.ts"), "w", encoding="utf-8") as f:
            f.write(BASE_CONTENT)
        with open(os.path.join(output_dir_str, "MessagePackCodec.ts"), "w", encoding="utf-8") as f:
            f.write(CODEC_CONTENT)
        with open(os.path.join(output_dir_str, "UnityStructs.ts"), "w", encoding="utf-8") as f:
            f.write(UNITY_STRUCTS_CONTENT)
        with open(os.path.join(output_dir_str, "ExportedClass.ts"), "w", encoding="utf-8") as f:
            f.write(EXPORTED_CLASS_CONTENT)

        proc = TypeProcessor()
        discover_roots = [class_name]
        for extra_name in EXTRA_ROOT_CLASS_NAMES:
            if extra_name not in discover_roots:
                discover_roots.append(extra_name)

        for root in discover_roots:
            print(f"[*] Discovering dependencies for {root}...")
            proc.discover(root)

        print(f"[*] Found {len(proc.registry)} types. Generating files...")
        proc.generate_all(output_dir_str)

        root_clean = class_name.split(".")[-1].replace("+", "_")
        found_root = None
        for r in proc.registry.keys():
            if r == root_clean or r.endswith("_" + root_clean):
                found_root = r
                break
        target = found_root if found_root else root_clean
        proc.write_json_schema(schema_output_dir_str, target)
        if not full_schema:
            apply_focused_schema_file(
                os.path.join(schema_output_dir_str, f"{target}.schema.json"),
                target,
            )

        with open(os.path.join(output_dir_str, "index.ts"), "w", encoding="utf-8") as f:

            f.write(f"/* Auto-generated by {SCRIPT_NAME} at {datetime.now().isoformat()} */\n")
            f.write(f"import {{ {target} }} from './{target}';\n\n")
            f.write("import './UnionRegistry';\n\n")
            f.write(f"export * from './{target}';\n")
            f.write("export * from './UnityStructs';\n")
            f.write("export * from './MessagePackCodec';\n")
            f.write("export * from './MessagePackBase';\n\n")
            f.write("export * from './ExportedClass';\n\n")

        print("[+] Done.")

    except Exception as e:
        print(f"[!] Error: {e}")
        traceback.print_exc()
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--game", required=True)
    parser.add_argument(
        "--full-schema",
        action="store_true",
        help="Generate the full DataManager schema without focused pruning.",
    )
    parser.add_argument(
        "--full-classes",
        action="store_true",
        help="Generate full classes without focused member filtering.",
    )
    parser.add_argument(
        "--output-dir",
        default=OUTPUT_DIR,
        help=f"Class output directory (default: {OUTPUT_DIR})",
    )
    parser.add_argument(
        "--schema-output-dir",
        default=SCHEMA_OUTPUT_DIR,
        help=f"Schema output directory (default: {SCHEMA_OUTPUT_DIR})",
    )
    args = parser.parse_args()

    run(
        game=Path(args.game),
        output_dir=Path(args.output_dir),
        schema_output_dir=Path(args.schema_output_dir),
        full_schema=bool(args.full_schema),
        full_classes=bool(args.full_classes),
    )
