BASE_CLASS_NAME = "FinalizedNotification"
CHILD_CLASS_NAMES = {
    "FinalizedFaithNotification",
    "FinalizedItemNotification",
    "FinalizedFollowerNotification",
    "FinalizedRelationshipNotification",
    "FinalizedNotificationSimple",
}


def render_finalized_notification_methods(class_name):
    if class_name == BASE_CLASS_NAME:
        return _render_base_methods()
    if class_name in CHILD_CLASS_NAMES:
        return _render_child_passthrough_methods()
    return []


def _render_base_methods():
    return [
        "  private static readonly TAG_BASE = 0;",
        "  private static readonly TAG_FAITH = 1;",
        "  private static readonly TAG_ITEM = 2;",
        "  private static readonly TAG_FOLLOWER = 3;",
        "  private static readonly TAG_RELATIONSHIP = 4;",
        "",
        "  public toMsgPackObject(): any {",
        "    if (this === null || this === undefined) {",
        "      return null;",
        "    }",
        "",
        "    const rawWire = MessagePackObject.prototype.toMsgPackObject.call(this);",
        "    const payload = FinalizedNotification.unwrapUnionPayload(rawWire);",
        "",
        "    let tag = FinalizedNotification.tryMapCtorNameToTag(",
        "      (this as any)?.constructor?.name,",
        "    );",
        "",
        "    if (tag === null) {",
        "      const unionTag = FinalizedNotification.tryReadUnionTag(rawWire);",
        "      tag = FinalizedNotification.mapUnionTagToPolymorphicTag(unionTag);",
        "    }",
        "",
        "    if (tag === null) {",
        "      throw new Error(",
        "        `Unsupported FinalizedNotification subtype: ${(this as any)?.constructor?.name ?? 'unknown'}`,",
        "      );",
        "    }",
        "",
        "    return [tag, payload];",
        "  }",
        "",
        "  public static createFromMsgPackObject<T extends MessagePackObject>(",
        "    this: new () => T,",
        "    obj: any,",
        "  ): T | null {",
        "    return FinalizedNotification.deserializePolymorphic(obj) as unknown as T | null;",
        "  }",
        "",
        "  public static createFromJSON<T extends MessagePackObject>(",
        "    this: new () => T,",
        "    json: any,",
        "  ): T | null {",
        "    if (json === null || json === undefined) {",
        "      return null;",
        "    }",
        "",
        "    if (Array.isArray(json)) {",
        "      return FinalizedNotification.deserializePolymorphic(json) as unknown as T | null;",
        "    }",
        "",
        "    return MessagePackObject.createFromJSON.call(",
        "      FinalizedNotification as unknown as typeof MessagePackObject,",
        "      json,",
        "    ) as unknown as T | null;",
        "  }",
        "",
        "  private static deserializePolymorphic(",
        "    source: any,",
        "  ): FinalizedNotification | null {",
        "    if (source === null || source === undefined) {",
        "      return null;",
        "    }",
        "",
        "    if (!Array.isArray(source)) {",
        "      return null;",
        "    }",
        "",
        "    if (source.length < 2) {",
        "      throw new Error('FinalizedNotification: expected array with >= 2 items.');",
        "    }",
        "",
        "    const tag = FinalizedNotification.tryParsePolymorphicTag(source[0]);",
        "    if (tag === null) {",
        "      return null;",
        "    }",
        "",
        "    const payloadIndex = source.length >= 3 ? 2 : 1;",
        "    const payload = FinalizedNotification.decodePossiblyCompressedPayload(",
        "      source[payloadIndex],",
        "    );",
        "",
        "    const unionTag = FinalizedNotification.mapPolymorphicTagToUnionTag(tag);",
        "    if (unionTag === null) {",
        "      return null;",
        "    }",
        "",
        "    return MessagePackObject.createFromMsgPackObject.call(",
        "      FinalizedNotification as unknown as typeof MessagePackObject,",
        "      [unionTag, payload],",
        "    ) as unknown as FinalizedNotification | null;",
        "  }",
        "",
        "  private static tryReadUnionTag(value: any): number | null {",
        "    if (!Array.isArray(value) || value.length < 2) {",
        "      return null;",
        "    }",
        "    return FinalizedNotification.tryCoerceTagNumber(value[0]);",
        "  }",
        "",
        "  private static unwrapUnionPayload(value: any): any {",
        "    if (Array.isArray(value) && value.length >= 2) {",
        "      const maybeTag = FinalizedNotification.tryCoerceTagNumber(value[0]);",
        "      if (maybeTag !== null) {",
        "        return value[1];",
        "      }",
        "    }",
        "    return value;",
        "  }",
        "",
        "  private static tryMapCtorNameToTag(name: unknown): number | null {",
        "    if (typeof name !== 'string') {",
        "      return null;",
        "    }",
        "",
        "    switch (name) {",
        "      case 'FinalizedFaithNotification':",
        "        return FinalizedNotification.TAG_FAITH;",
        "      case 'FinalizedItemNotification':",
        "        return FinalizedNotification.TAG_ITEM;",
        "      case 'FinalizedFollowerNotification':",
        "        return FinalizedNotification.TAG_FOLLOWER;",
        "      case 'FinalizedRelationshipNotification':",
        "        return FinalizedNotification.TAG_RELATIONSHIP;",
        "      case 'FinalizedNotificationSimple':",
        "        return FinalizedNotification.TAG_BASE;",
        "      default:",
        "        return null;",
        "    }",
        "  }",
        "",
        "  private static tryParsePolymorphicTag(value: unknown): number | null {",
        "    if (typeof value === 'number' || typeof value === 'bigint') {",
        "      return FinalizedNotification.tryCoerceTagNumber(value);",
        "    }",
        "",
        "    if (typeof value !== 'string') {",
        "      return null;",
        "    }",
        "",
        "    const numericTag = FinalizedNotification.tryCoerceTagNumber(value);",
        "    if (numericTag !== null) {",
        "      return numericTag;",
        "    }",
        "",
        "    let normalized = value.trim();",
        "    if (normalized.length === 0) {",
        "      return null;",
        "    }",
        "",
        "    const dotIndex = normalized.lastIndexOf('.');",
        "    if (dotIndex >= 0 && dotIndex < normalized.length - 1) {",
        "      normalized = normalized.slice(dotIndex + 1);",
        "    }",
        "",
        "    normalized = normalized.toLowerCase();",
        "    if (normalized.startsWith('finalized')) {",
        "      normalized = normalized.slice(9);",
        "    }",
        "    if (normalized.endsWith('notification')) {",
        "      normalized = normalized.slice(0, -12);",
        "    }",
        "",
        "    switch (normalized) {",
        "      case 'faith':",
        "        return FinalizedNotification.TAG_FAITH;",
        "      case 'item':",
        "        return FinalizedNotification.TAG_ITEM;",
        "      case 'follower':",
        "        return FinalizedNotification.TAG_FOLLOWER;",
        "      case 'relationship':",
        "        return FinalizedNotification.TAG_RELATIONSHIP;",
        "      case 'base':",
        "      case 'simple':",
        "        return FinalizedNotification.TAG_BASE;",
        "      default:",
        "        return null;",
        "    }",
        "  }",
        "",
        "  private static tryCoerceTagNumber(value: unknown): number | null {",
        "    let numeric: number;",
        "    if (typeof value === 'bigint') {",
        "      numeric = Number(value);",
        "    } else if (typeof value === 'number') {",
        "      numeric = value;",
        "    } else if (typeof value === 'string') {",
        "      const parsed = Number(value);",
        "      if (!Number.isFinite(parsed)) {",
        "        return null;",
        "      }",
        "      numeric = parsed;",
        "    } else {",
        "      return null;",
        "    }",
        "",
        "    if (!Number.isInteger(numeric)) {",
        "      return null;",
        "    }",
        "",
        "    if (numeric < FinalizedNotification.TAG_BASE || numeric > FinalizedNotification.TAG_RELATIONSHIP) {",
        "      return null;",
        "    }",
        "",
        "    return numeric;",
        "  }",
        "",
        "  private static mapPolymorphicTagToUnionTag(tag: number): number | null {",
        "    switch (tag) {",
        "      case FinalizedNotification.TAG_BASE:",
        "        return 4;",
        "      case FinalizedNotification.TAG_FAITH:",
        "        return 0;",
        "      case FinalizedNotification.TAG_ITEM:",
        "        return 1;",
        "      case FinalizedNotification.TAG_FOLLOWER:",
        "        return 2;",
        "      case FinalizedNotification.TAG_RELATIONSHIP:",
        "        return 3;",
        "      default:",
        "        return null;",
        "    }",
        "  }",
        "",
        "  private static mapUnionTagToPolymorphicTag(tag: number | null): number | null {",
        "    switch (tag) {",
        "      case 4:",
        "        return FinalizedNotification.TAG_BASE;",
        "      case 0:",
        "        return FinalizedNotification.TAG_FAITH;",
        "      case 1:",
        "        return FinalizedNotification.TAG_ITEM;",
        "      case 2:",
        "        return FinalizedNotification.TAG_FOLLOWER;",
        "      case 3:",
        "        return FinalizedNotification.TAG_RELATIONSHIP;",
        "      default:",
        "        return null;",
        "    }",
        "  }",
        "",
    ]


def _render_child_passthrough_methods():
    return [
        "  public static createFromMsgPackObject<T extends MessagePackObject>(",
        "    this: new () => T,",
        "    obj: any,",
        "  ): T | null {",
        "    return MessagePackObject.createFromMsgPackObject.call(",
        "      this as unknown as typeof MessagePackObject,",
        "      obj,",
        "    ) as unknown as T | null;",
        "  }",
        "",
        "  public static createFromJSON<T extends MessagePackObject>(",
        "    this: new () => T,",
        "    json: any,",
        "  ): T | null {",
        "    return MessagePackObject.createFromJSON.call(",
        "      this as unknown as typeof MessagePackObject,",
        "      json,",
        "    ) as unknown as T | null;",
        "  }",
        "",
    ]
