TARGET_CLASS_NAME = "StructuresData_Ranchable_Animal"


def render_ranchable_animal_methods(class_name):
    if class_name != TARGET_CLASS_NAME:
        return []

    return [
        "  private static readonly SERIALIZED_LENGTH = 34;",
        "",
        "  public toMsgPackObject(): any {",
        "    const wire: any[] = new Array(StructuresData_Ranchable_Animal.SERIALIZED_LENGTH).fill(null);",
        "    wire[0] = StructuresData_Ranchable_Animal.toI32(this.Type);",
        "    wire[1] = StructuresData_Ranchable_Animal.toI32(this.Age);",
        "    wire[2] = StructuresData_Ranchable_Animal.toI32(this.ID);",
        "    wire[3] = StructuresData_Ranchable_Animal.toF32(this.Satiation);",
        "    wire[4] = StructuresData_Ranchable_Animal.toF32(this.TimeSincePoop);",
        "    wire[5] = StructuresData_Ranchable_Animal.toBool(this.MilkedToday);",
        "    wire[6] = StructuresData_Ranchable_Animal.toBool(this.MilkedReady);",
        "    wire[7] = StructuresData_Ranchable_Animal.toBool(this.WorkedToday);",
        "    wire[8] = StructuresData_Ranchable_Animal.toBool(this.WorkedReady);",
        "    wire[9] = StructuresData_Ranchable_Animal.toBool(this.EatenToday);",
        "    wire[10] = StructuresData_Ranchable_Animal.toBool(this.PetToday);",
        "    wire[11] = StructuresData_Ranchable_Animal.toBool(this.PlayerMadeHappyToday);",
        "    wire[12] = StructuresData_Ranchable_Animal.toF32(this._adoration);",
        "    wire[13] = StructuresData_Ranchable_Animal.toI32(this.Level);",
        "    wire[14] = StructuresData_Ranchable_Animal.toI32(this.FavouriteFood);",
        "    wire[15] = StructuresData_Ranchable_Animal.toBool(this.IsFavouriteFoodRevealed);",
        "    wire[16] = StructuresData_Ranchable_Animal.toI32(this.State);",
        "    wire[17] = StructuresData_Ranchable_Animal.toI32(this.Ailment);",
        "    wire[18] = StructuresData_Ranchable_Animal.toF32(this.AilmentGameTime);",
        "    wire[19] = StructuresData_Ranchable_Animal.toI32(this.HappyAmount);",
        "    wire[20] = this.LastPosition ? this.LastPosition.toMsgPackObject() : null;",
        "    wire[21] = this.GivenName ?? null;",
        "    wire[22] = StructuresData_Ranchable_Animal.toI32(this.GrowthStage);",
        "    wire[23] = StructuresData_Ranchable_Animal.toI32(this.growthRate);",
        "    wire[24] = StructuresData_Ranchable_Animal.toI32(this.Horns);",
        "    wire[25] = StructuresData_Ranchable_Animal.toI32(this.Ears);",
        "    wire[26] = StructuresData_Ranchable_Animal.toI32(this.Head);",
        "    wire[27] = StructuresData_Ranchable_Animal.toI32(this.Colour);",
        "    wire[28] = StructuresData_Ranchable_Animal.toF32(this.Speed);",
        "    wire[29] = StructuresData_Ranchable_Animal.toF32(this.TimeSinceLastWash);",
        "    wire[30] = StructuresData_Ranchable_Animal.toBool(this.BestFriend);",
        "    wire[31] = StructuresData_Ranchable_Animal.toBool(this.RacedToday);",
        "    wire[32] = StructuresData_Ranchable_Animal.toF32(this.Injured);",
        "    wire[33] = StructuresData_Ranchable_Animal.toF32(this.FeralCalming);",
        "    return wire;",
        "  }",
        "",
        "  public static createFromMsgPackObject<T extends MessagePackObject>(",
        "    this: new () => T,",
        "    obj: any,",
        "  ): T | null {",
        "    return StructuresData_Ranchable_Animal.fromRanchableWire(obj) as unknown as T | null;",
        "  }",
        "",
        "  public static createFromJSON<T extends MessagePackObject>(",
        "    this: new () => T,",
        "    json: any,",
        "  ): T | null {",
        "    return StructuresData_Ranchable_Animal.fromRanchableJson(json) as unknown as T | null;",
        "  }",
        "",
        "  private static fromRanchableWire(source: any): StructuresData_Ranchable_Animal | null {",
        "    if (source === null || source === undefined) {",
        "      return null;",
        "    }",
        "",
        "    const animal = StructuresData_Ranchable_Animal.createDefault();",
        "",
        "    if (Array.isArray(source)) {",
        "      for (let index = 0; index < source.length; index++) {",
        "        StructuresData_Ranchable_Animal.applyWireValue(animal, index, source[index]);",
        "      }",
        "      return animal;",
        "    }",
        "",
        "    if (typeof source === 'object') {",
        "      for (const [rawKey, value] of Object.entries(source as Record<string, unknown>)) {",
        "        const keyIndex = StructuresData_Ranchable_Animal.toNumericIndex(rawKey);",
        "        if (keyIndex === null) {",
        "          continue;",
        "        }",
        "",
        "        StructuresData_Ranchable_Animal.applyWireValue(animal, keyIndex, value);",
        "      }",
        "      return animal;",
        "    }",
        "",
        "    return animal;",
        "  }",
        "",
        "  private static fromRanchableJson(source: any): StructuresData_Ranchable_Animal | null {",
        "    if (source === null || source === undefined) {",
        "      return null;",
        "    }",
        "",
        "    if (Array.isArray(source)) {",
        "      return StructuresData_Ranchable_Animal.fromRanchableWire(source);",
        "    }",
        "",
        "    if (typeof source !== 'object') {",
        "      return StructuresData_Ranchable_Animal.createDefault();",
        "    }",
        "",
        "    const animal = StructuresData_Ranchable_Animal.createDefault();",
        "    animal.Type = StructuresData_Ranchable_Animal.toI32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 0, 'Type'),",
        "    ) as InventoryItem_ITEM_TYPE;",
        "    animal.Age = StructuresData_Ranchable_Animal.toI32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 1, 'Age'),",
        "    );",
        "    animal.ID = StructuresData_Ranchable_Animal.toI32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 2, 'ID'),",
        "    );",
        "    animal.Satiation = StructuresData_Ranchable_Animal.toF32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 3, 'Satiation'),",
        "    );",
        "    animal.TimeSincePoop = StructuresData_Ranchable_Animal.toF32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 4, 'TimeSincePoop'),",
        "    );",
        "    animal.MilkedToday = StructuresData_Ranchable_Animal.toBool(",
        "      StructuresData_Ranchable_Animal.readValue(source, 5, 'MilkedToday'),",
        "    );",
        "    animal.MilkedReady = StructuresData_Ranchable_Animal.toBool(",
        "      StructuresData_Ranchable_Animal.readValue(source, 6, 'MilkedReady'),",
        "    );",
        "    animal.WorkedToday = StructuresData_Ranchable_Animal.toBool(",
        "      StructuresData_Ranchable_Animal.readValue(source, 7, 'WorkedToday'),",
        "    );",
        "    animal.WorkedReady = StructuresData_Ranchable_Animal.toBool(",
        "      StructuresData_Ranchable_Animal.readValue(source, 8, 'WorkedReady'),",
        "    );",
        "    animal.EatenToday = StructuresData_Ranchable_Animal.toBool(",
        "      StructuresData_Ranchable_Animal.readValue(source, 9, 'EatenToday'),",
        "    );",
        "    animal.PetToday = StructuresData_Ranchable_Animal.toBool(",
        "      StructuresData_Ranchable_Animal.readValue(source, 10, 'PetToday'),",
        "    );",
        "    animal.PlayerMadeHappyToday = StructuresData_Ranchable_Animal.toBool(",
        "      StructuresData_Ranchable_Animal.readValue(source, 11, 'PlayerMadeHappyToday'),",
        "    );",
        "    animal._adoration = StructuresData_Ranchable_Animal.toF32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 12, '_adoration'),",
        "    );",
        "    animal.Level = StructuresData_Ranchable_Animal.toI32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 13, 'Level'),",
        "    );",
        "    animal.FavouriteFood = StructuresData_Ranchable_Animal.toI32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 14, 'FavouriteFood'),",
        "    ) as InventoryItem_ITEM_TYPE;",
        "    animal.IsFavouriteFoodRevealed = StructuresData_Ranchable_Animal.toBool(",
        "      StructuresData_Ranchable_Animal.readValue(source, 15, 'IsFavouriteFoodRevealed'),",
        "    );",
        "    animal.State = StructuresData_Ranchable_Animal.toI32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 16, 'State'),",
        "    ) as Interaction_Ranchable_State;",
        "    animal.Ailment = StructuresData_Ranchable_Animal.toI32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 17, 'Ailment'),",
        "    ) as Interaction_Ranchable_Ailment;",
        "    animal.AilmentGameTime = StructuresData_Ranchable_Animal.toF32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 18, 'AilmentGameTime'),",
        "    );",
        "    animal.HappyAmount = StructuresData_Ranchable_Animal.toI32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 19, 'HappyAmount'),",
        "    );",
        "    animal.LastPosition = StructuresData_Ranchable_Animal.toVector3(",
        "      StructuresData_Ranchable_Animal.readValue(source, 20, 'LastPosition'),",
        "    );",
        "    animal.GivenName = StructuresData_Ranchable_Animal.toNullableString(",
        "      StructuresData_Ranchable_Animal.readValue(source, 21, 'GivenName'),",
        "    );",
        "    animal.GrowthStage = StructuresData_Ranchable_Animal.toI32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 22, 'GrowthStage'),",
        "    );",
        "    animal.growthRate = StructuresData_Ranchable_Animal.toI32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 23, 'growthRate'),",
        "    ) as Interaction_Ranchable_GrowthRate;",
        "    animal.Horns = StructuresData_Ranchable_Animal.toI32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 24, 'Horns'),",
        "    );",
        "    animal.Ears = StructuresData_Ranchable_Animal.toI32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 25, 'Ears'),",
        "    );",
        "    animal.Head = StructuresData_Ranchable_Animal.toI32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 26, 'Head'),",
        "    );",
        "    animal.Colour = StructuresData_Ranchable_Animal.toI32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 27, 'Colour'),",
        "    );",
        "    animal.Speed = StructuresData_Ranchable_Animal.toF32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 28, 'Speed'),",
        "    );",
        "    animal.TimeSinceLastWash = StructuresData_Ranchable_Animal.toF32(",
        "      StructuresData_Ranchable_Animal.readValue(source, 29, 'TimeSinceLastWash'),",
        "    );",
        "    animal.BestFriend = StructuresData_Ranchable_Animal.toBool(",
        "      StructuresData_Ranchable_Animal.readValue(source, 30, 'BestFriend'),",
        "    );",
        "    animal.RacedToday = StructuresData_Ranchable_Animal.toBool(",
        "      StructuresData_Ranchable_Animal.readValue(source, 31, 'RacedToday'),",
        "    );",
        "",
        "    const injured = StructuresData_Ranchable_Animal.readValue(source, 32, 'Injured');",
        "    if (injured !== null && injured !== undefined) {",
        "      animal.Injured = StructuresData_Ranchable_Animal.toF32(injured);",
        "    }",
        "",
        "    const injuredLegacy = StructuresData_Ranchable_Animal.readValue(source, 122, 'Injured');",
        "    if (injuredLegacy !== null && injuredLegacy !== undefined) {",
        "      animal.Injured = StructuresData_Ranchable_Animal.toF32(injuredLegacy);",
        "    }",
        "",
        "    const feralCalming = StructuresData_Ranchable_Animal.readValue(source, 33, 'FeralCalming');",
        "    if (feralCalming !== null && feralCalming !== undefined) {",
        "      animal.FeralCalming = StructuresData_Ranchable_Animal.toF32(feralCalming);",
        "    }",
        "",
        "    const feralCalmingLegacy = StructuresData_Ranchable_Animal.readValue(source, 123, 'FeralCalming');",
        "    if (feralCalmingLegacy !== null && feralCalmingLegacy !== undefined) {",
        "      animal.FeralCalming = StructuresData_Ranchable_Animal.toF32(feralCalmingLegacy);",
        "    }",
        "",
        "    return animal;",
        "  }",
        "",
        "  private static applyWireValue(",
        "    animal: StructuresData_Ranchable_Animal,",
        "    keyIndex: number,",
        "    value: unknown,",
        "  ): void {",
        "    switch (keyIndex) {",
        "      case 0:",
        "        animal.Type = StructuresData_Ranchable_Animal.toI32(value) as InventoryItem_ITEM_TYPE;",
        "        break;",
        "      case 1:",
        "        animal.Age = StructuresData_Ranchable_Animal.toI32(value);",
        "        break;",
        "      case 2:",
        "        animal.ID = StructuresData_Ranchable_Animal.toI32(value);",
        "        break;",
        "      case 3:",
        "        animal.Satiation = StructuresData_Ranchable_Animal.toF32(value);",
        "        break;",
        "      case 4:",
        "        animal.TimeSincePoop = StructuresData_Ranchable_Animal.toF32(value);",
        "        break;",
        "      case 5:",
        "        animal.MilkedToday = StructuresData_Ranchable_Animal.toBool(value);",
        "        break;",
        "      case 6:",
        "        animal.MilkedReady = StructuresData_Ranchable_Animal.toBool(value);",
        "        break;",
        "      case 7:",
        "        animal.WorkedToday = StructuresData_Ranchable_Animal.toBool(value);",
        "        break;",
        "      case 8:",
        "        animal.WorkedReady = StructuresData_Ranchable_Animal.toBool(value);",
        "        break;",
        "      case 9:",
        "        animal.EatenToday = StructuresData_Ranchable_Animal.toBool(value);",
        "        break;",
        "      case 10:",
        "        animal.PetToday = StructuresData_Ranchable_Animal.toBool(value);",
        "        break;",
        "      case 11:",
        "        animal.PlayerMadeHappyToday = StructuresData_Ranchable_Animal.toBool(value);",
        "        break;",
        "      case 12:",
        "        animal._adoration = StructuresData_Ranchable_Animal.toF32(value);",
        "        break;",
        "      case 13:",
        "        animal.Level = StructuresData_Ranchable_Animal.toI32(value);",
        "        break;",
        "      case 14:",
        "        animal.FavouriteFood = StructuresData_Ranchable_Animal.toI32(value) as InventoryItem_ITEM_TYPE;",
        "        break;",
        "      case 15:",
        "        animal.IsFavouriteFoodRevealed = StructuresData_Ranchable_Animal.toBool(value);",
        "        break;",
        "      case 16:",
        "        animal.State = StructuresData_Ranchable_Animal.toI32(value) as Interaction_Ranchable_State;",
        "        break;",
        "      case 17:",
        "        animal.Ailment = StructuresData_Ranchable_Animal.toI32(value) as Interaction_Ranchable_Ailment;",
        "        break;",
        "      case 18:",
        "        animal.AilmentGameTime = StructuresData_Ranchable_Animal.toF32(value);",
        "        break;",
        "      case 19:",
        "        animal.HappyAmount = StructuresData_Ranchable_Animal.toI32(value);",
        "        break;",
        "      case 20:",
        "        animal.LastPosition = StructuresData_Ranchable_Animal.toVector3(value);",
        "        break;",
        "      case 21:",
        "        animal.GivenName = StructuresData_Ranchable_Animal.toNullableString(value);",
        "        break;",
        "      case 22:",
        "        animal.GrowthStage = StructuresData_Ranchable_Animal.toI32(value);",
        "        break;",
        "      case 23:",
        "        animal.growthRate = StructuresData_Ranchable_Animal.toI32(value) as Interaction_Ranchable_GrowthRate;",
        "        break;",
        "      case 24:",
        "        animal.Horns = StructuresData_Ranchable_Animal.toI32(value);",
        "        break;",
        "      case 25:",
        "        animal.Ears = StructuresData_Ranchable_Animal.toI32(value);",
        "        break;",
        "      case 26:",
        "        animal.Head = StructuresData_Ranchable_Animal.toI32(value);",
        "        break;",
        "      case 27:",
        "        animal.Colour = StructuresData_Ranchable_Animal.toI32(value);",
        "        break;",
        "      case 28:",
        "        animal.Speed = StructuresData_Ranchable_Animal.toF32(value);",
        "        break;",
        "      case 29:",
        "        animal.TimeSinceLastWash = StructuresData_Ranchable_Animal.toF32(value);",
        "        break;",
        "      case 30:",
        "        animal.BestFriend = StructuresData_Ranchable_Animal.toBool(value);",
        "        break;",
        "      case 31:",
        "        animal.RacedToday = StructuresData_Ranchable_Animal.toBool(value);",
        "        break;",
        "      case 32:",
        "      case 122:",
        "        if (value !== null && value !== undefined) {",
        "          animal.Injured = StructuresData_Ranchable_Animal.toF32(value);",
        "        }",
        "        break;",
        "      case 33:",
        "      case 123:",
        "        if (value !== null && value !== undefined) {",
        "          animal.FeralCalming = StructuresData_Ranchable_Animal.toF32(value);",
        "        }",
        "        break;",
        "      default:",
        "        break;",
        "    }",
        "  }",
        "",
        "  private static createDefault(): StructuresData_Ranchable_Animal {",
        "    const animal = new StructuresData_Ranchable_Animal();",
        "    animal.Type = 0 as InventoryItem_ITEM_TYPE;",
        "    animal.Age = 0;",
        "    animal.ID = 0;",
        "    animal.Satiation = 0;",
        "    animal.Injured = 0;",
        "    animal.FeralCalming = 0;",
        "    animal.TimeSincePoop = 0;",
        "    animal.TimeSinceLastWash = 0;",
        "    animal.MilkedToday = false;",
        "    animal.MilkedReady = false;",
        "    animal.HappyAmount = 0;",
        "    animal.PlayerMadeHappyToday = false;",
        "    animal.RacedToday = false;",
        "    animal.WorkedToday = false;",
        "    animal.WorkedReady = false;",
        "    animal.EatenToday = false;",
        "    animal.IsFavouriteFoodRevealed = false;",
        "    animal.FavouriteFood = 0 as InventoryItem_ITEM_TYPE;",
        "    animal.BestFriend = false;",
        "    animal.PetToday = false;",
        "    animal.State = 0 as Interaction_Ranchable_State;",
        "    animal.Ailment = 0 as Interaction_Ranchable_Ailment;",
        "    animal.AilmentGameTime = 0;",
        "    animal._adoration = 0;",
        "    animal.Level = 0;",
        "    animal.GivenName = null;",
        "    animal.GrowthStage = 0;",
        "    animal.growthRate = 0 as Interaction_Ranchable_GrowthRate;",
        "    animal.LastPosition = new Vector3();",
        "    animal.LastPosition.x = 0;",
        "    animal.LastPosition.y = 0;",
        "    animal.LastPosition.z = 0;",
        "    animal.Horns = 0;",
        "    animal.Ears = 0;",
        "    animal.Head = 0;",
        "    animal.Colour = 0;",
        "    animal.Speed = 0;",
        "    animal.CauseOfDeath = 0 as Interaction_Ranchable_CauseOfDeath;",
        "    return animal;",
        "  }",
        "",
        "  private static readValue(source: any, index: number, name: string): unknown {",
        "    return StructuresData_Ranchable_Animal.readKeyedValue(source, index, name);",
        "  }",
        "",
        "  private static toI32(value: unknown): number {",
        "    return StructuresData_Ranchable_Animal.toIntegerValue(value, 0, true);",
        "  }",
        "",
        "  private static toF32(value: unknown): number {",
        "    return StructuresData_Ranchable_Animal.toFloatValue(value, 0, true);",
        "  }",
        "",
        "  private static toBool(value: unknown): boolean {",
        "    return StructuresData_Ranchable_Animal.toBooleanValue(value);",
        "  }",
        "",
        "  private static toNullableString(value: unknown): string | null {",
        "    return StructuresData_Ranchable_Animal.toNullableStringValue(value);",
        "  }",
        "",
        "  private static toVector3(value: unknown): Vector3 {",
        "    const parsedFromWire = Vector3.createFromMsgPackObject(value);",
        "    if (parsedFromWire) {",
        "      return parsedFromWire;",
        "    }",
        "",
        "    const parsedFromJson = Vector3.createFromJSON(value);",
        "    if (parsedFromJson) {",
        "      return parsedFromJson;",
        "    }",
        "",
        "    const fallback = new Vector3();",
        "    fallback.x = 0;",
        "    fallback.y = 0;",
        "    fallback.z = 0;",
        "    return fallback;",
        "  }",
        "",
        "  private static toNumericIndex(value: string | number): number | null {",
        "    return StructuresData_Ranchable_Animal.toNumericIndexValue(value);",
        "  }",
        "",
    ]
