TARGET_CLASS_NAME = "StoryObjectiveData"


def render_story_objective_data_methods(class_name):
    if class_name != TARGET_CLASS_NAME:
        return []

    return [
        "  private static readonly MAX_CUSTOM_DEPTH = 64;",
        "",
        "  public toMsgPackObject(): any {",
        "    return StoryObjectiveData.toStoryWire(this, 0);",
        "  }",
        "",
        "  public static createFromMsgPackObject<T extends MessagePackObject>(",
        "    this: new () => T,",
        "    obj: any,",
        "  ): T | null {",
        "    return StoryObjectiveData.fromStoryWire(obj, 0) as unknown as T | null;",
        "  }",
        "",
        "  public static createFromJSON<T extends MessagePackObject>(",
        "    this: new () => T,",
        "    json: any,",
        "  ): T | null {",
        "    return StoryObjectiveData.fromStoryJson(json, 0) as unknown as T | null;",
        "  }",
        "",
        "  private static toStoryWire(value: any, depth: number): any {",
        "    if (value === null || value === undefined) {",
        "      return null;",
        "    }",
        "",
        "    if (typeof value === 'number' || typeof value === 'bigint') {",
        "      return StoryObjectiveData.normalizeInt(value);",
        "    }",
        "",
        "    const node =",
        "      value instanceof StoryObjectiveData",
        "        ? value",
        "        : StoryObjectiveData.fromStoryJson(value, depth);",
        "",
        "    if (!node) {",
        "      return null;",
        "    }",
        "",
        "    if (depth > StoryObjectiveData.MAX_CUSTOM_DEPTH) {",
        "      return StoryObjectiveData.normalizeInt(node.UniqueStoryID);",
        "    }",
        "",
        "    const wire: any[] = new Array(9).fill(null);",
        "    wire[0] = StoryObjectiveData.normalizeInt(node.UniqueStoryID);",
        "    wire[1] = typeof node.GiveQuestTerm === 'string' ? node.GiveQuestTerm : null;",
        "    wire[2] = StoryObjectiveData.normalizeInt(node.QuestIndex);",
        "    wire[3] = StoryObjectiveData.normalizeInt(node.Target1FollowerID);",
        "    wire[4] = StoryObjectiveData.normalizeInt(node.Target2FollowerID);",
        "    wire[5] = StoryObjectiveData.normalizeInt(node.DeadBodyFollowerID);",
        "    wire[6] = StoryObjectiveData.normalizeInt(node.QuestGiverRequiresID);",
        "    wire[7] = StoryObjectiveData.normalizeAssetName(node.AssetName);",
        "",
        "    if (Array.isArray(node.ChilldStoryItems) && node.ChilldStoryItems.length > 0) {",
        "      wire[8] = node.ChilldStoryItems.map((child) =>",
        "        StoryObjectiveData.toStoryWire(child, depth + 1),",
        "      );",
        "    }",
        "",
        "    for (const [unknownKey, unknownValue] of node.unknownKeys.entries()) {",
        "      const idx = StoryObjectiveData.toNumericIndex(unknownKey);",
        "      if (idx === null || idx <= 8) {",
        "        continue;",
        "      }",
        "      if (idx >= wire.length) {",
        "        const previousLength = wire.length;",
        "        wire.length = idx + 1;",
        "        wire.fill(null, previousLength, wire.length);",
        "      }",
        "      wire[idx] = StoryObjectiveData.toUnknownWire(unknownValue, depth + 1);",
        "    }",
        "",
        "    return wire;",
        "  }",
        "",
        "  private static fromStoryWire(value: any, depth: number): StoryObjectiveData | null {",
        "    if (value === null || value === undefined) {",
        "      return null;",
        "    }",
        "",
        "    if (typeof value === 'number' || typeof value === 'bigint') {",
        "      return StoryObjectiveData.fromStoryId(value);",
        "    }",
        "",
        "    if (!Array.isArray(value) && typeof value !== 'object') {",
        "      return null;",
        "    }",
        "",
        "    const node = new StoryObjectiveData();",
        "    node.UniqueStoryID = StoryObjectiveData.normalizeInt(",
        "      StoryObjectiveData.readValue(value, 0, 'UniqueStoryID'),",
        "    );",
        "    node.GiveQuestTerm = StoryObjectiveData.toNullableString(",
        "      StoryObjectiveData.readValue(value, 1, 'GiveQuestTerm'),",
        "    );",
        "    node.QuestIndex = StoryObjectiveData.normalizeInt(",
        "      StoryObjectiveData.readValue(value, 2, 'QuestIndex'),",
        "    );",
        "    node.Target1FollowerID = StoryObjectiveData.normalizeInt(",
        "      StoryObjectiveData.readValue(value, 3, 'Target1FollowerID'),",
        "    );",
        "    node.Target2FollowerID = StoryObjectiveData.normalizeInt(",
        "      StoryObjectiveData.readValue(value, 4, 'Target2FollowerID'),",
        "    );",
        "    node.DeadBodyFollowerID = StoryObjectiveData.normalizeInt(",
        "      StoryObjectiveData.readValue(value, 5, 'DeadBodyFollowerID'),",
        "    );",
        "    node.QuestGiverRequiresID = StoryObjectiveData.normalizeInt(",
        "      StoryObjectiveData.readValue(value, 6, 'QuestGiverRequiresID'),",
        "    );",
        "",
        "    const key7 = StoryObjectiveData.readValue(value, 7, 'AssetName');",
        "    const key8 = StoryObjectiveData.readValue(value, 8, 'ChilldStoryItems');",
        "",
        "    if (Array.isArray(key7) && !Array.isArray(key8)) {",
        "      node.AssetName = StoryObjectiveData.normalizeAssetName(key8);",
        "      node.ChilldStoryItems = StoryObjectiveData.readChildrenFromWire(",
        "        key7,",
        "        depth + 1,",
        "      );",
        "    } else {",
        "      node.AssetName = StoryObjectiveData.normalizeAssetName(key7);",
        "      node.ChilldStoryItems = StoryObjectiveData.readChildrenFromWire(",
        "        key8,",
        "        depth + 1,",
        "      );",
        "    }",
        "",
        "    StoryObjectiveData.readUnknownValues(value, node);",
        "    return node;",
        "  }",
        "",
        "  private static fromStoryJson(value: any, depth: number): StoryObjectiveData | null {",
        "    if (value === null || value === undefined) {",
        "      return null;",
        "    }",
        "",
        "    if (typeof value === 'number' || typeof value === 'bigint') {",
        "      return StoryObjectiveData.fromStoryId(value);",
        "    }",
        "",
        "    if (Array.isArray(value)) {",
        "      return StoryObjectiveData.fromStoryWire(value, depth);",
        "    }",
        "",
        "    if (typeof value !== 'object') {",
        "      return null;",
        "    }",
        "",
        "    const node = new StoryObjectiveData();",
        "    node.UniqueStoryID = StoryObjectiveData.normalizeInt(",
        "      StoryObjectiveData.readValue(value, 0, 'UniqueStoryID'),",
        "    );",
        "    node.GiveQuestTerm = StoryObjectiveData.toNullableString(",
        "      StoryObjectiveData.readValue(value, 1, 'GiveQuestTerm'),",
        "    );",
        "    node.QuestIndex = StoryObjectiveData.normalizeInt(",
        "      StoryObjectiveData.readValue(value, 2, 'QuestIndex'),",
        "    );",
        "    node.Target1FollowerID = StoryObjectiveData.normalizeInt(",
        "      StoryObjectiveData.readValue(value, 3, 'Target1FollowerID'),",
        "    );",
        "    node.Target2FollowerID = StoryObjectiveData.normalizeInt(",
        "      StoryObjectiveData.readValue(value, 4, 'Target2FollowerID'),",
        "    );",
        "    node.DeadBodyFollowerID = StoryObjectiveData.normalizeInt(",
        "      StoryObjectiveData.readValue(value, 5, 'DeadBodyFollowerID'),",
        "    );",
        "    node.QuestGiverRequiresID = StoryObjectiveData.normalizeInt(",
        "      StoryObjectiveData.readValue(value, 6, 'QuestGiverRequiresID'),",
        "    );",
        "",
        "    const key7 = StoryObjectiveData.readValue(value, 7, 'AssetName');",
        "    const key8 = StoryObjectiveData.readValue(value, 8, 'ChilldStoryItems');",
        "",
        "    if (Array.isArray(key7) && !Array.isArray(key8)) {",
        "      node.AssetName = StoryObjectiveData.normalizeAssetName(key8);",
        "      node.ChilldStoryItems = StoryObjectiveData.readChildrenFromJson(",
        "        key7,",
        "        depth + 1,",
        "      );",
        "    } else {",
        "      node.AssetName = StoryObjectiveData.normalizeAssetName(key7);",
        "      node.ChilldStoryItems = StoryObjectiveData.readChildrenFromJson(",
        "        key8,",
        "        depth + 1,",
        "      );",
        "    }",
        "",
        "    StoryObjectiveData.readUnknownValues(value, node);",
        "    return node;",
        "  }",
        "",
        "  private static readChildrenFromWire(value: any, depth: number): StoryObjectiveData[] | null {",
        "    if (!Array.isArray(value)) {",
        "      return null;",
        "    }",
        "    const children: StoryObjectiveData[] = [];",
        "    for (const item of value) {",
        "      const child = StoryObjectiveData.fromStoryWire(item, depth);",
        "      if (child) {",
        "        children.push(child);",
        "      }",
        "    }",
        "    return children;",
        "  }",
        "",
        "  private static readChildrenFromJson(value: any, depth: number): StoryObjectiveData[] | null {",
        "    if (!Array.isArray(value)) {",
        "      return null;",
        "    }",
        "    const children: StoryObjectiveData[] = [];",
        "    for (const item of value) {",
        "      const child = StoryObjectiveData.fromStoryJson(item, depth);",
        "      if (child) {",
        "        children.push(child);",
        "      }",
        "    }",
        "    return children;",
        "  }",
        "",
        "  private static fromStoryId(id: number | bigint): StoryObjectiveData {",
        "    const node = new StoryObjectiveData();",
        "    node.UniqueStoryID = StoryObjectiveData.normalizeInt(id);",
        "    node.GiveQuestTerm = null;",
        "    node.QuestIndex = 0;",
        "    node.Target1FollowerID = 0;",
        "    node.Target2FollowerID = 0;",
        "    node.DeadBodyFollowerID = 0;",
        "    node.QuestGiverRequiresID = 0;",
        "    node.AssetName = null;",
        "    node.ChilldStoryItems = null;",
        "    return node;",
        "  }",
        "",
        "  private static toUnknownWire(value: any, depth: number): any {",
        "    if (value === null || value === undefined) {",
        "      return null;",
        "    }",
        "    if (typeof value === 'number' || typeof value === 'bigint') {",
        "      return value;",
        "    }",
        "    if (value instanceof StoryObjectiveData) {",
        "      return StoryObjectiveData.toStoryWire(value, depth);",
        "    }",
        "    if (Array.isArray(value)) {",
        "      return value.map((item) => StoryObjectiveData.toUnknownWire(item, depth + 1));",
        "    }",
        "    if (typeof value === 'object') {",
        "      const out: any = {};",
        "      for (const [k, v] of Object.entries(value)) {",
        "        out[k] = StoryObjectiveData.toUnknownWire(v, depth + 1);",
        "      }",
        "      return out;",
        "    }",
        "    return value;",
        "  }",
        "",
        "  private static readUnknownValues(source: any, node: StoryObjectiveData): void {",
        "    const knownNames = new Set([",
        "      'UniqueStoryID',",
        "      'GiveQuestTerm',",
        "      'QuestIndex',",
        "      'Target1FollowerID',",
        "      'Target2FollowerID',",
        "      'DeadBodyFollowerID',",
        "      'QuestGiverRequiresID',",
        "      'AssetName',",
        "      'ChilldStoryItems',",
        "    ]);",
        "",
        "    if (Array.isArray(source)) {",
        "      for (let idx = 9; idx < source.length; idx++) {",
        "        if (source[idx] !== undefined) {",
        "          node.unknownKeys.set(idx, source[idx]);",
        "        }",
        "      }",
        "      return;",
        "    }",
        "",
        "    for (const [rawKey, rawValue] of Object.entries(source as Record<string, any>)) {",
        "      if (knownNames.has(rawKey)) {",
        "        continue;",
        "      }",
        "",
        "      const keyIndex = StoryObjectiveData.toNumericIndex(rawKey);",
        "      if (keyIndex !== null && keyIndex >= 0 && keyIndex <= 8) {",
        "        continue;",
        "      }",
        "",
        "      if (rawKey.startsWith('__UNKNOWN_')) {",
        "        const original = rawKey.replace('__UNKNOWN_', '').replace(/__$/, '');",
        "        const normalized = StoryObjectiveData.toNumericIndex(original);",
        "        node.unknownKeys.set(normalized ?? original, rawValue);",
        "        continue;",
        "      }",
        "",
        "      node.unknownKeys.set(keyIndex ?? rawKey, rawValue);",
        "    }",
        "  }",
        "",
        "  private static readValue(source: any, index: number, name: string): any {",
        "    return StoryObjectiveData.readKeyedValue(source, index, name);",
        "  }",
        "",
        "  private static normalizeInt(value: any): number {",
        "    return StoryObjectiveData.toIntegerValue(value);",
        "  }",
        "",
        "  private static normalizeAssetName(value: any): string | null {",
        "    if (typeof value !== 'string') {",
        "      return null;",
        "    }",
        "    return value.length > 0 ? value : null;",
        "  }",
        "",
        "  private static toNullableString(value: any): string | null {",
        "    return StoryObjectiveData.toNullableStringValue(value, false);",
        "  }",
        "",
        "  private static toNumericIndex(value: string | number): number | null {",
        "    return StoryObjectiveData.toNumericIndexValue(value);",
        "  }",
        "",
    ]
