import { FollowerTrait_TraitType } from '@/generated/classes/FollowerTrait_TraitType';

export const GoodTraits = [
  FollowerTrait_TraitType.FalseIdols,
  FollowerTrait_TraitType.Cannibal,
  FollowerTrait_TraitType.Gullible,
  FollowerTrait_TraitType.ConstructionEnthusiast,
  FollowerTrait_TraitType.Coprophiliac,
  FollowerTrait_TraitType.DesensitisedToDeath,
  FollowerTrait_TraitType.Disciplinarian,
  FollowerTrait_TraitType.Faithful,
  FollowerTrait_TraitType.HateElderly,
  FollowerTrait_TraitType.Industrious,
  FollowerTrait_TraitType.IronStomach,
  FollowerTrait_TraitType.Libertarian,
  FollowerTrait_TraitType.LoveElderly,
  FollowerTrait_TraitType.LoveOfSickPeople,
  FollowerTrait_TraitType.Materialistic,
  FollowerTrait_TraitType.MushroomBanned,
  FollowerTrait_TraitType.MushroomEncouraged,
  FollowerTrait_TraitType.NaturallyObedient,
  FollowerTrait_TraitType.SacrificeEnthusiast,
  FollowerTrait_TraitType.Zealous,
  FollowerTrait_TraitType.Immortal,
  FollowerTrait_TraitType.DontStarve,
  FollowerTrait_TraitType.GrassEater,
  FollowerTrait_TraitType.SermonEnthusiast,
  FollowerTrait_TraitType.Disciple,
  FollowerTrait_TraitType.Lustful,
  FollowerTrait_TraitType.Fashionable,
  FollowerTrait_TraitType.Nudist,
  FollowerTrait_TraitType.MusicLover,
  FollowerTrait_TraitType.Fertility,
  FollowerTrait_TraitType.DoctrinalExtremist,
  FollowerTrait_TraitType.ViolentExtremist,
  FollowerTrait_TraitType.Allegiance,
  FollowerTrait_TraitType.Hedonism,
  FollowerTrait_TraitType.Asceticism,
  FollowerTrait_TraitType.Unrepentant,
  FollowerTrait_TraitType.RoyalPooper,
  FollowerTrait_TraitType.CriminalReformed,
  FollowerTrait_TraitType.MissionaryInspired,
  FollowerTrait_TraitType.MissionaryExcited,
  FollowerTrait_TraitType.Pettable,
  FollowerTrait_TraitType.MarriedHappily,
  FollowerTrait_TraitType.ProudParent,
  FollowerTrait_TraitType.Polyamory,
  FollowerTrait_TraitType.BishopOfCult,
  FollowerTrait_TraitType.WarmBlooded,
  FollowerTrait_TraitType.ChosenOne,
  FollowerTrait_TraitType.PureBlood,
  FollowerTrait_TraitType.PureBlood_1,
  FollowerTrait_TraitType.PureBlood_2,
  FollowerTrait_TraitType.PureBlood_3,
  FollowerTrait_TraitType.MutatedVisual,
  FollowerTrait_TraitType.Frigidophile,
  FollowerTrait_TraitType.WinterExcited,
  FollowerTrait_TraitType.RotstonePooper,
  FollowerTrait_TraitType.WolfHater,
  FollowerTrait_TraitType.MutatedImmune,
  FollowerTrait_TraitType.WinterBody,
  FollowerTrait_TraitType.AnimalLover,
  FollowerTrait_TraitType.LightningEnthusiast,
  FollowerTrait_TraitType.HappilyWidowed,
  FollowerTrait_TraitType.DeepSleeper,
  FollowerTrait_TraitType.LockedLoyal,
  FollowerTrait_TraitType.Masochistic,
  FollowerTrait_TraitType.SeenGod,
  FollowerTrait_TraitType.Pacifist,
  FollowerTrait_TraitType.Heavyweight,
  FollowerTrait_TraitType.FreezeImmune,
  FollowerTrait_TraitType.InfusibleSnowman,
  FollowerTrait_TraitType.BornToTheRot,
  FollowerTrait_TraitType.MasterfulSnowman,
  FollowerTrait_TraitType.Nudist,
  FollowerTrait_TraitType.FluteLover,
  FollowerTrait_TraitType.MusicLover,
  FollowerTrait_TraitType.FreezeImmune,
  FollowerTrait_TraitType.EmbraceRot,
  FollowerTrait_TraitType.RejectRot,
  FollowerTrait_TraitType.FurnaceAnimal,
  FollowerTrait_TraitType.FurnaceFollower,
  FollowerTrait_TraitType.RemoveRot,
  FollowerTrait_TraitType.ColdEnthusiast,
  FollowerTrait_TraitType.WorkThroughBlizzard,
];

export const ExclusiveTraits = [
  [FollowerTrait_TraitType.Germophobe, FollowerTrait_TraitType.Coprophiliac],
  [
    FollowerTrait_TraitType.FearOfSickPeople,
    FollowerTrait_TraitType.LoveOfSickPeople,
  ],
  [FollowerTrait_TraitType.Cynical, FollowerTrait_TraitType.Gullible],
  [FollowerTrait_TraitType.Disciplinarian, FollowerTrait_TraitType.Libertarian],
  [FollowerTrait_TraitType.Sickly, FollowerTrait_TraitType.IronStomach],
  [
    FollowerTrait_TraitType.NaturallyObedient,
    FollowerTrait_TraitType.NaturallySkeptical,
  ],
  [
    FollowerTrait_TraitType.SacrificeEnthusiast,
    FollowerTrait_TraitType.AgainstSacrifice,
  ],
  [FollowerTrait_TraitType.Faithful, FollowerTrait_TraitType.Faithless],
  [FollowerTrait_TraitType.Industrious, FollowerTrait_TraitType.Lazy],
  [
    FollowerTrait_TraitType.MushroomEncouraged,
    FollowerTrait_TraitType.MushroomBanned,
  ],
  [FollowerTrait_TraitType.LoveElderly, FollowerTrait_TraitType.HateElderly],
  [
    FollowerTrait_TraitType.FearOfDeath,
    FollowerTrait_TraitType.DesensitisedToDeath,
  ],
  [FollowerTrait_TraitType.Hedonism, FollowerTrait_TraitType.Asceticism],
  [FollowerTrait_TraitType.Virtuous, FollowerTrait_TraitType.Unrepentant],
  [FollowerTrait_TraitType.Celibate, FollowerTrait_TraitType.Lustful],
  [FollowerTrait_TraitType.CriminalReformed, FollowerTrait_TraitType.Lazy],
  [
    FollowerTrait_TraitType.MarriedUnhappily,
    FollowerTrait_TraitType.MarriedHappily,
  ],
  [
    FollowerTrait_TraitType.ProudParent,
    FollowerTrait_TraitType.OverworkedParent,
  ],
  [FollowerTrait_TraitType.Drowsy, FollowerTrait_TraitType.Industrious],
  [FollowerTrait_TraitType.ColdBlooded, FollowerTrait_TraitType.WarmBlooded],
  [
    FollowerTrait_TraitType.HappilyWidowed,
    FollowerTrait_TraitType.GrievingWidow,
  ],
  [FollowerTrait_TraitType.LockedLoyal, FollowerTrait_TraitType.Masochistic],
  [FollowerTrait_TraitType.Heavyweight, FollowerTrait_TraitType.Lightweight],
  [FollowerTrait_TraitType.Hibernation, FollowerTrait_TraitType.Aestivation],
  [FollowerTrait_TraitType.Mutated, FollowerTrait_TraitType.MutatedImmune],
  [FollowerTrait_TraitType.MutatedVisual, FollowerTrait_TraitType.Mutated],
  [
    FollowerTrait_TraitType.MutatedImmune,
    FollowerTrait_TraitType.MutatedVisual,
  ],
  [FollowerTrait_TraitType.EmbraceRot, FollowerTrait_TraitType.RejectRot],
  [
    FollowerTrait_TraitType.MasterfulSnowman,
    FollowerTrait_TraitType.ShoddySnowman,
  ],
  [FollowerTrait_TraitType.Pacifist, FollowerTrait_TraitType.Argumentative],
];

export const UniqueTraits = [
  FollowerTrait_TraitType.BishopOfCult,
  FollowerTrait_TraitType.Immortal,
  FollowerTrait_TraitType.Disciple,
  FollowerTrait_TraitType.DontStarve,
  FollowerTrait_TraitType.Blind,
  FollowerTrait_TraitType.BornToTheRot,
];
