from __future__ import annotations

import argparse
import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, cast

import UnityPy
import UnityPy.classes

DEFAULT_OUTPUT_DIR = Path("src/generated/data/assets")
DEFAULT_GENERATED_ROOT = Path("src/generated")
EXTRACTED_VERSION_ASSET_NAME = "version"


@dataclass(frozen=True)
class TextureCandidate:
    name: str
    width: int
    height: int
    env_path: Path
    path_id: int


@dataclass(frozen=True)
class TextureRequirement:
    name: str
    expected_width: int | None
    expected_height: int | None
    atlas_path: Path


@dataclass(frozen=True)
class SelectedTexture:
    name: str
    expected_width: int | None
    expected_height: int | None
    path_id: int


def normalize_data_dir(path: Path) -> Path:
    path = path.expanduser().resolve()
    if not path.exists():
        raise SystemExit(f"ERROR: path does not exist: {path}")

    if path.is_file():
        parent = path.parent
        if parent.name.endswith("_Data"):
            return parent
        raise SystemExit(f"ERROR: expected a game root or *_Data directory, got file: {path}")

    if path.name.endswith("_Data"):
        return path

    direct_candidate = path / "Cult Of The Lamb_Data"
    if direct_candidate.is_dir():
        return direct_candidate

    data_folder_candidate = path / f"{path.name}_Data"
    if data_folder_candidate.is_dir():
        return data_folder_candidate

    raise SystemExit(
        "ERROR: could not resolve *_Data directory from path:\n"
        f"  {path}\n"
        "Pass --game pointing to the game root or *_Data folder."
    )


def iter_files(root: Path) -> Iterable[Path]:
    for dirpath, _, filenames in os.walk(root):
        for filename in filenames:
            yield Path(dirpath) / filename


def load_unity_env(path: Path):
    try:
        return UnityPy.load(str(path))
    except Exception:
        return None


def text_asset_payload(data: UnityPy.classes.TextAsset) -> bytes:
    payload = data.m_Script
    if isinstance(payload, str):
        return payload.encode("utf-8", "surrogateescape")
    return bytes(payload)


def read_extracted_game_version(output_dir: Path) -> str:
    version_asset_path = output_dir / EXTRACTED_VERSION_ASSET_NAME
    if not version_asset_path.is_file():
        return ""
    return version_asset_path.read_text(encoding="utf-8", errors="ignore").strip()


def write_game_version_module(generated_root: Path, extracted_game_version: str) -> None:
    generated_root.mkdir(parents=True, exist_ok=True)
    output_path = generated_root / "version.ts"
    output_path.write_text(
        (
            "// Generated by extraction/cmd_assets.py\n"
            f"export const EXTRACTED_GAME_VERSION = {json.dumps(extracted_game_version)};\n"
        ),
        encoding="utf-8",
    )
    print(f"Wrote extracted game version module: {output_path}")


def write_text_asset(output_dir: Path, data: UnityPy.classes.TextAsset, env_path: Path) -> None:
    name = (data.m_Name or "").strip()
    if not name:
        return

    output_path = output_dir / name
    if output_path.exists() and name != EXTRACTED_VERSION_ASSET_NAME:
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    print(f"Extracting {name} from {env_path}")
    output_path.write_bytes(text_asset_payload(data))


def collect_text_assets_and_candidates(
    data_dir: Path, output_dir: Path
) -> tuple[dict[str, list[TextureCandidate]], list[Path]]:
    texture_candidates: dict[str, list[TextureCandidate]] = {}
    env_paths: list[Path] = []

    for env_path in iter_files(data_dir):
        env = load_unity_env(env_path)
        if env is None:
            continue

        env_paths.append(env_path)
        for obj in env.objects:
            if obj.type.name == "TextAsset":
                data = cast(UnityPy.classes.TextAsset, obj.read())
                write_text_asset(output_dir, data, env_path)
                continue

            if obj.type.name != "Texture2D":
                continue

            data = cast(UnityPy.classes.Texture2D, obj.read())
            texture_name = (data.m_Name or "").strip()
            if not texture_name:
                continue

            texture_candidates.setdefault(texture_name, []).append(
                TextureCandidate(
                    name=texture_name,
                    width=int(data.m_Width),
                    height=int(data.m_Height),
                    env_path=env_path,
                    path_id=int(obj.path_id),
                )
            )

    return texture_candidates, env_paths


def parse_atlas_texture_requirements(atlas_path: Path) -> list[TextureRequirement]:
    requirements: list[TextureRequirement] = []
    lines = atlas_path.read_text(encoding="utf-8", errors="ignore").splitlines()
    for index, raw_line in enumerate(lines):
        line = raw_line.strip()
        if not line.endswith(".png"):
            continue

        texture_name = line[:-4]
        expected_width: int | None = None
        expected_height: int | None = None

        first_non_empty_after_page: str | None = None
        for look_ahead in range(index + 1, min(index + 8, len(lines))):
            candidate = lines[look_ahead].strip()
            if not candidate:
                continue
            first_non_empty_after_page = candidate
            break

        if first_non_empty_after_page and first_non_empty_after_page.startswith("size:"):
            size_value = first_non_empty_after_page.split(":", 1)[1].strip()
            if "," in size_value:
                raw_width, raw_height = size_value.split(",", 1)
                try:
                    expected_width = int(raw_width.strip())
                    expected_height = int(raw_height.strip())
                except ValueError:
                    expected_width = None
                    expected_height = None

        requirements.append(
            TextureRequirement(
                name=texture_name,
                expected_width=expected_width,
                expected_height=expected_height,
                atlas_path=atlas_path,
            )
        )

    return requirements


def collect_required_texture_requirements(
    output_dir: Path,
) -> dict[str, list[TextureRequirement]]:
    required_by_name: dict[str, list[TextureRequirement]] = {}
    for atlas_path in sorted(output_dir.glob("*.atlas")):
        requirements = parse_atlas_texture_requirements(atlas_path)
        for requirement in requirements:
            required_by_name.setdefault(requirement.name, []).append(requirement)
    return required_by_name


def get_preferred_requirement_size(
    requirements: list[TextureRequirement],
) -> tuple[int | None, int | None]:
    sized = [
        (requirement.expected_width, requirement.expected_height)
        for requirement in requirements
        if requirement.expected_width is not None
        and requirement.expected_height is not None
    ]
    if not sized:
        return None, None

    return max(sized, key=lambda pair: pair[0] * pair[1])


def choose_best_texture_candidate(
    candidates: list[TextureCandidate],
    expected_width: int | None,
    expected_height: int | None,
) -> TextureCandidate:
    if expected_width is None or expected_height is None:
        return max(candidates, key=lambda candidate: candidate.width * candidate.height)

    def score(candidate: TextureCandidate) -> tuple[int, int, int]:
        area = candidate.width * candidate.height
        if candidate.width == expected_width and candidate.height == expected_height:
            return (0, 0, -area)
        if candidate.width >= expected_width and candidate.height >= expected_height:
            overshoot = (candidate.width - expected_width) + (candidate.height - expected_height)
            return (1, overshoot, -area)

        deficit = abs(candidate.width - expected_width) + abs(candidate.height - expected_height)
        return (2, deficit, -area)

    return min(candidates, key=score)


def select_texture_sources(
    required_by_name: dict[str, list[TextureRequirement]],
    texture_candidates: dict[str, list[TextureCandidate]],
) -> tuple[dict[Path, dict[int, SelectedTexture]], set[str], list[str]]:
    selected_by_env: dict[Path, dict[int, SelectedTexture]] = {}
    missing_textures: set[str] = set()
    selection_warnings: list[str] = []

    for texture_name, requirements in sorted(required_by_name.items()):
        candidates = texture_candidates.get(texture_name)
        if not candidates:
            missing_textures.add(texture_name)
            continue

        expected_width, expected_height = get_preferred_requirement_size(requirements)
        selected = choose_best_texture_candidate(candidates, expected_width, expected_height)

        selected_by_env.setdefault(selected.env_path, {})[selected.path_id] = SelectedTexture(
            name=texture_name,
            expected_width=expected_width,
            expected_height=expected_height,
            path_id=selected.path_id,
        )

        if (
            expected_width is not None
            and expected_height is not None
            and (selected.width != expected_width or selected.height != expected_height)
        ):
            selection_warnings.append(
                "Atlas size mismatch for "
                f"{texture_name}.png: expected {expected_width}x{expected_height}, "
                f"selected {selected.width}x{selected.height} from {selected.env_path}"
            )

    return selected_by_env, missing_textures, selection_warnings


def extract_texture_to_png(
    output_dir: Path,
    data: UnityPy.classes.Texture2D,
    env_path: Path,
    expected_width: int | None,
    expected_height: int | None,
) -> bool:
    texture_name = (data.m_Name or "").strip()
    if not texture_name:
        return False

    output_path = output_dir / f"{texture_name}.png"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        image = data.image
        image.save(output_path)
    except Exception as exc:
        print(f"Failed to extract {texture_name}.png from {env_path}: {exc}")
        return False

    print(f"Extracting {texture_name}.png from {env_path}")
    if (
        expected_width is not None
        and expected_height is not None
        and (image.width != expected_width or image.height != expected_height)
    ):
        print(
            "WARNING: extracted texture size differs from atlas size for "
            f"{texture_name}.png: expected {expected_width}x{expected_height}, "
            f"got {image.width}x{image.height}"
        )
    return True


def extract_textures(
    output_dir: Path,
    env_paths: list[Path],
    selected_by_env: dict[Path, dict[int, SelectedTexture]],
) -> dict[Path, dict[int, SelectedTexture]]:
    remaining_by_env: dict[Path, dict[int, SelectedTexture]] = {
        path: dict(selected) for path, selected in selected_by_env.items()
    }

    for env_path in env_paths:
        textures_for_env = remaining_by_env.get(env_path)
        if not textures_for_env:
            continue

        env = load_unity_env(env_path)
        if env is None:
            continue

        for obj in env.objects:
            if obj.type.name != "Texture2D":
                continue

            path_id = int(obj.path_id)
            selected = textures_for_env.get(path_id)
            if selected is None:
                continue

            data = cast(UnityPy.classes.Texture2D, obj.read())
            texture_name = (data.m_Name or "").strip()
            if texture_name != selected.name:
                continue

            if not extract_texture_to_png(
                output_dir,
                data,
                env_path,
                selected.expected_width,
                selected.expected_height,
            ):
                continue

            del textures_for_env[path_id]

        if textures_for_env:
            remaining_by_env[env_path] = textures_for_env
        elif env_path in remaining_by_env:
            del remaining_by_env[env_path]

        if not remaining_by_env:
            break

    return remaining_by_env


def run(*, game: Path, output_dir: Path, generated_root: Path | None = None) -> None:
    data_dir = normalize_data_dir(game)
    output_dir = output_dir.expanduser().resolve()
    generated_root = (
        generated_root.expanduser().resolve()
        if generated_root is not None
        else output_dir.parent.parent.resolve()
    )
    output_dir.mkdir(parents=True, exist_ok=True)

    texture_candidates, env_paths = collect_text_assets_and_candidates(data_dir, output_dir)
    write_game_version_module(generated_root, read_extracted_game_version(output_dir))

    required_by_name = collect_required_texture_requirements(output_dir)

    if not required_by_name:
        print("No .atlas texture references were found in the output directory.")
        print("Extraction of assets has been completed")
        return

    selected_by_env, missing_textures, selection_warnings = select_texture_sources(
        required_by_name, texture_candidates
    )
    for warning in selection_warnings:
        print(f"WARNING: {warning}")

    unresolved_by_env = extract_textures(output_dir, env_paths, selected_by_env)

    for env_path, selected in unresolved_by_env.items():
        if selected:
            missing_in_env = sorted(item.name for item in selected.values())
            print(f"Some textures cannot be found in {env_path}: {missing_in_env}")

    if missing_textures:
        print(f"Some textures cannot be found: {sorted(missing_textures)}")

    print("Extraction of assets has been completed")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Extract TextAssets and atlas-referenced Texture2D images from "
            "Cult of the Lamb Unity data."
        )
    )
    parser.add_argument(
        "--game",
        required=True,
        help="Game root path or *_Data folder path (required).",
    )
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help=f"Output directory (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--generated-root",
        default=str(DEFAULT_GENERATED_ROOT),
        help=f"Directory where version.ts is written (default: {DEFAULT_GENERATED_ROOT})",
    )
    args = parser.parse_args()

    data_dir = normalize_data_dir(Path(args.game))
    output_dir = Path(args.output_dir).expanduser().resolve()
    generated_root = Path(args.generated_root).expanduser().resolve()
    run(game=data_dir, output_dir=output_dir, generated_root=generated_root)


if __name__ == "__main__":
    main()
